#!/usr/bin/env bash
set -eu

# Function to print error messages and exit
error() {
  echo -e "\e[1;31m$1\e[0m" >&2
  exit 1
}

# Function to print success messages
success() {
  echo -e "\e[1;32m$1\e[0m"
}

# Check if running in the NixOS installer environment
[ -e /etc/NIXOS ] || error "Not running in the NixOS installer environment."

success "Running in the NixOS installer environment."

# Check for root privileges
[ "$(id -u)" -eq 0 ] || error "This script must be run as root."

# Check if the nixos-config repository already exists
if [ -d nixos-config ]; then
  success "Repository already exists. Resetting and cleaning..."
  cd nixos-config && git fetch --all && git reset --hard && git clean -dfx || error "Failed to fetch, reset, and clean the repository."
else
  # Clone the repository if it does not exist
  git clone https://github.com/andreszb/nixos-config.git && cd nixos-config || error "Failed to clone the repository."
fi

# Print the current directory
success "Current directory: $(pwd)"

# Run disko to format and mount the disk
sudo nix run --extra-experimental-features nix-command --extra-experimental-features flakes \
  github:nix-community/disko -- --mode zap_create_mount ./hosts/nixos/disk-config.nix || error "Disko operation failed."

# Setup the configuration files
USER_HOME="/mnt/home/andreszb"
sudo mkdir -p "$USER_HOME/nixos-config" && sudo cp -r * "$USER_HOME/nixos-config" || error "Failed to copy configuration files to $USER_HOME/nixos-config."
sudo ln -sfn "$USER_HOME/nixos-config" /mnt/etc/nixos || error "Failed to link configuration files to /mnt/etc/nixos."
cd /mnt/etc/nixos || error "Failed to change directory to /mnt/etc/nixos."

# Install NixOS
ARCH=$(uname -m)

case "$ARCH" in
  x86_64)
    FLAKE_TARGET="x86_64-linux"
    ;;
  *)
    error "Unsupported architecture: $ARCH"
    ;;
esac

sudo nixos-generate-config --no-filesystems --root /mnt --show-hardware-config > /mnt/etc/nixos/hardware-configuration.nix || error "Failed to generate NixOS configuration."
sudo nixos-install --flake .#$FLAKE_TARGET "$@" || error "NixOS installation failed."
sudo chmod -R 775 /mnt/etc/nixos || error "Failed to set permissions for /mnt/etc/nixos."

# Prompt for reboot
read -p "Do you want to reboot now? (y/yes) " choice
case "$choice" in
  y|Y|yes|YES )
    success "Rebooting..."
    sudo reboot
    ;;
  * )
    echo -e "\e[1;33mReboot skipped.\e[0m"
    ;;
esac
